/*
 * shaders.c - vertex and pixel shaders used in gles2 mode
 */

// vertex shader for gles2
static const char vertex_shader[] =
"attribute vec3 position;\n"
"attribute vec3 normal;\n"
"attribute vec2 uv;\n"
"\n"
"uniform mat4 ModelViewMatrix;\n"
"uniform mat4 CameraProjectionMatrix;\n"
"uniform mat4 NormalMatrix;\n"
"// light position in view space\n"
"\n"
"varying vec3 N;\n"
"varying vec3 V;\n"
"varying vec2 oUV;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec4 pos = vec4(position, 1.0);\n"
"   // None of the vectors are normalized until in the fragment shader\n"
"// Calculate the normal vector for this vertex, in view space (\n"
"// multiply by NormalMatrix)\n"
"    N = (NormalMatrix * vec4(normal, 0.0)).xyz;\n"
"    // Calculate the view vector\n"
"    pos = ModelViewMatrix * pos;\n"
"    V = pos.xyz;\n"
"    // Calculate the light vector for this vertex\n"
"// calculate half angle\n"
"\n"
"    oUV = uv;\n"
"    // Transform the position to clip coordinates\n"
"    gl_Position = CameraProjectionMatrix * pos;\n"
"}";

// fragment shader for gles2
static const char fragment_shader[] =
"\n"
"precision highp float;\n"
"\n"
"uniform vec4 MaterialColor;\n"
"uniform vec4 LightSourcePosition;\n"
"uniform sampler2D DiffuseMap;\n"
"\n"
"varying vec3 N;\n"
"varying vec3 V;\n"
"varying vec2 oUV;\n"
"\n"
"void main(void)\n"
"{\n"
"    //discard;\n"
"    vec3 l = normalize(LightSourcePosition.xyz - V);\n"
"    vec3 n = normalize(N);\n"
"    vec3 h = normalize(l - normalize(V));\n"    
"\n"
"    vec4 diffuse = vec4(vec3(max(dot(l, n), 0.0)), 1.0);\n"
"    // get bump map vector, again expand from range-compressed\n"
"    vec4 diffCol = texture2D(DiffuseMap, oUV);\n"
"    // modulate diffuseMap with base material color\n"
"    //float depth = (1.0 - gl_FragCoord.z)*40.0;\n"
"    gl_FragColor = MaterialColor * diffCol * diffuse;\n"
"    //gl_FragColor = vec4(depth, depth, depth, 1.0) ;\n"
" //   add  specular\n"
"    // materials that have more red in them are shinnier\n"
"    float grey = ( 0.21*diffCol.r + 0.72*diffCol.g + 0.07*diffCol.b ) + 0.2;\n"
"    gl_FragColor.xyz += pow(max(0.0, dot(n, h)), 25.0 ) * diffCol.xyz;\n"
"}";
