/*
 * shaders.c - vertex and pixel shaders used in gles2 mode
 */

// vertex shader for gles2
static const char vertex_shader[] =
"attribute vec3 position;\n"
"attribute vec3 normal;\n"
"attribute vec2 uv;\n"
"\n"
"uniform mat4 ModelViewMatrix;\n"
"uniform mat4 ModelViewProjectionMatrix;\n"
"uniform mat4 NormalMatrix;\n"
"// light position in view space\n"
"uniform vec4 LightSourcePosition;\n"
"\n"
"varying lowp vec3 L;\n"
"varying lowp vec3 N;\n"
"varying lowp vec3 H;\n"
"varying lowp vec2 oUV;\n"
"//varying float depth;\n"
"\n"
"void main(void)\n"
"{\n"
"    vec4 pos = vec4(position, 1.0);\n"
"   // None of the vectors are normalized until in the fragment shader\n"
"// Calculate the normal vector for this vertex, in view space (\n"
"// multiply by NormalMatrix)\n"
"    N = vec3(NormalMatrix * vec4(normal, 0.0));\n"
"    // Calculate the light vector for this vertex\n"
"    L = vec3(LightSourcePosition - (ModelViewMatrix * pos));\n"
"    // Calculate the view vector\n"
"    lowp vec3 V = vec3(ModelViewMatrix * pos);\n"
"// calculate half angle\n"
"    H = L - V;\n"
"\n"
"    oUV = uv;\n"
"    // Transform the position to clip coordinates\n"
"    gl_Position = ModelViewProjectionMatrix * pos;\n"
"    //depth = 1.0-gl_Position.z/40.0;\n"
"}";

// fragment shader for gles2
static const char fragment_shader[] =
"\n"
"uniform vec4 MaterialColor;\n"
"uniform sampler2D DiffuseMap;\n"
"\n"
"varying lowp vec3 L;\n"
"varying lowp vec3 N;\n"
"varying lowp vec3 H;\n"
"varying lowp vec2 oUV;\n"
"//varying  float depth;\n"
"\n"
"void main(void)\n"
"{\n"
"    lowp vec3 l = normalize(L);\n"
"    lowp vec3 n = normalize(N);\n"
"    lowp vec3 h = normalize(H);\n"    
"\n"
"    vec4 diffuse = vec4(vec3(max(dot(l, n), 0.0)), 1.0);\n"
"    // get bump map vector, again expand from range-compressed\n"
"    vec4 diffCol = texture2D(DiffuseMap, oUV);\n"
"    // modulate diffuseMap with base material color\n"
"    gl_FragColor = MaterialColor * diffCol * diffuse;\n"
"    //gl_FragColor = vec4(depth, depth, depth , 1.0) ;\n"
" //   add  specular\n"
"    // materials that have more red in them are shinnier\n"
"    float grey = 0.21*diffCol.r + 0.72*diffCol.g + 0.07*diffCol.b;\n"
"    gl_FragColor += pow(max(0.0, dot(n, h)), 7.0 ) * grey;\n"
"}";
